# Composite action to authenticate to OCI using GitHub Actions OIDC
# Exchanges GitHub OIDC token for OCI Access Token via JWT Bearer grant
# Based on: https://www.ateam-oracle.com/github-actions-oci-a-guide-to-secure-oidc-token-exchange
#
# Prerequisites:
#   1. Configure Identity Propagation Trust in OCI Identity Domains
#   2. Create OAuth application with JWT assertion grant
#   3. Add permissions: id-token: write in workflow
#
# Usage in workflow:
#   permissions:
#     id-token: write
#     contents: read
#   steps:
#     - uses: ./.github/actions/oci-oidc-auth
#       id: oci-auth
#       with:
#         oci_tenancy_ocid: ${{ secrets.OCI_CLI_TENANCY }}
#         oci_user_ocid: ${{ secrets.OCI_CLI_USER }}
#         oci_fingerprint: ${{ secrets.OCI_CLI_FINGERPRINT }}
#         oci_region: ${{ secrets.OCI_CLI_REGION }}
#         oci_api_key_content: ${{ secrets.OCI_CLI_KEY_CONTENT }}
#         oci_domain_url: ${{ secrets.OCI_DOMAIN_URL }}
#         oci_client_id: ${{ secrets.OCI_OIDC_CLIENT_ID }}
#         oci_client_secret: ${{ secrets.OCI_OIDC_CLIENT_SECRET }}
#
# Outputs:
#   oci_session_token: OCI Access Token
#   oci_session_key: OCI session private key (for API key fallback)
#   auth_method: 'oidc' or 'api_key'
name: 'OCI OIDC Authentication'
description: 'Exchanges GitHub OIDC token for OCI Access Token via JWT Bearer grant'

inputs:
  oci_tenancy_ocid:
    description: 'OCI Tenancy OCID'
    required: true
  oci_user_ocid:
    description: 'OCI User OCID'
    required: true
  oci_fingerprint:
    description: 'OCI API Key Fingerprint'
    required: true
  oci_region:
    description: 'OCI Region'
    required: true
    default: 'eu-paris-1'
  oci_api_key_content:
    description: 'OCI API Key Content (PEM) - used as fallback if OIDC exchange fails'
    required: true
  oci_domain_url:
    description: 'OCI Identity Domain URL (e.g., https://idcs-xxx.identity.oraclecloud.com)'
    required: false
    default: ''
  oci_client_id:
    description: 'OCI OIDC OAuth Application Client ID'
    required: false
    default: ''
  oci_client_secret:
    description: 'OCI OIDC OAuth Application Client Secret'
    required: false
    default: ''

outputs:
  oci_session_token:
    description: 'OCI Session Token (UPST)'
    value: ${{ steps.exchange.outputs.session_token }}
  oci_session_key:
    description: 'OCI Session Private Key'
    value: ${{ steps.exchange.outputs.session_key }}
  auth_method:
    description: 'Authentication method used (oidc or api_key)'
    value: ${{ steps.exchange.outputs.auth_method }}

runs:
  using: 'composite'
  steps:
    - name: Request GitHub OIDC token
      id: github_token
      shell: bash
      run: |
        # Request GitHub OIDC token
        # The audience should match what's configured in OCI Identity Provider

        # Check if OIDC is available (only on real GitHub runners)
        if [[ -z "$ACTIONS_ID_TOKEN_REQUEST_URL" || -z "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" ]]; then
          echo "::warning::GitHub OIDC not available (running locally or missing id-token permission)"
          echo "token=" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        GITHUB_TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=oci" | jq -r '.value' 2>/dev/null || echo "")

        if [[ -z "$GITHUB_TOKEN" || "$GITHUB_TOKEN" == "null" ]]; then
          echo "::warning::Failed to obtain GitHub OIDC token, will use API key fallback"
          echo "token=" >> "$GITHUB_OUTPUT"
        else
          echo "✓ GitHub OIDC token obtained"
          echo "token=$GITHUB_TOKEN" >> "$GITHUB_OUTPUT"
        fi

    - name: Install OCI CLI and dependencies
      shell: bash
      run: |
        if ! command -v oci &> /dev/null; then
          echo "Installing OCI CLI..."
          curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh | bash -s -- --accept-all-defaults
          echo "$HOME/bin" >> $GITHUB_PATH
        fi
        if ! command -v jq &> /dev/null; then
          sudo apt-get update && sudo apt-get install -y jq
        fi

    - name: Configure OCI API Key (for token exchange or fallback)
      shell: bash
      env:
        OCI_CLI_KEY: ${{ inputs.oci_api_key_content }}
      run: |
        mkdir -p ~/.oci
        printf '%s\n' "$OCI_CLI_KEY" > ~/.oci/oci_api_key.pem
        chmod 600 ~/.oci/oci_api_key.pem
        {
          echo "[DEFAULT]"
          echo "user=${{ inputs.oci_user_ocid }}"
          echo "fingerprint=${{ inputs.oci_fingerprint }}"
          echo "tenancy=${{ inputs.oci_tenancy_ocid }}"
          echo "region=${{ inputs.oci_region }}"
          echo "key_file=${HOME}/.oci/oci_api_key.pem"
        } > ~/.oci/config

    - name: Exchange GitHub OIDC token for OCI Access Token
      id: exchange
      shell: bash
      env:
        GITHUB_OIDC_TOKEN: ${{ steps.github_token.outputs.token }}
        OCI_API_KEY_CONTENT: ${{ inputs.oci_api_key_content }}
        OCI_DOMAIN_URL: ${{ inputs.oci_domain_url }}
        OCI_CLIENT_ID: ${{ inputs.oci_client_id }}
        OCI_CLIENT_SECRET: ${{ inputs.oci_client_secret }}
      run: |
        # Helper function to output multiline values to GITHUB_OUTPUT
        output_multiline() {
          local name="$1"
          local value="$2"
          {
            echo "${name}<<EOF_${name}"
            printf '%s\n' "$value"
            echo "EOF_${name}"
          } >> "$GITHUB_OUTPUT"
        }

        # Check if OIDC is configured
        if [[ -z "$GITHUB_OIDC_TOKEN" ]]; then
          echo "::warning::No GitHub OIDC token available, using API key authentication"
          echo "auth_method=api_key" >> "$GITHUB_OUTPUT"
          echo "session_token=" >> "$GITHUB_OUTPUT"
          output_multiline "session_key" "$OCI_API_KEY_CONTENT"
          exit 0
        fi

        if [[ -z "$OCI_DOMAIN_URL" || -z "$OCI_CLIENT_ID" || -z "$OCI_CLIENT_SECRET" ]]; then
          echo "::warning::OCI OIDC not fully configured (missing domain URL, client ID, or secret)"
          echo "::warning::Falling back to API key authentication"
          echo "auth_method=api_key" >> "$GITHUB_OUTPUT"
          echo "session_token=" >> "$GITHUB_OUTPUT"
          output_multiline "session_key" "$OCI_API_KEY_CONTENT"
          exit 0
        fi

        echo "Attempting OIDC token exchange via JWT Bearer grant..."

        # Exchange GitHub OIDC token for OCI Access Token via Identity Domains
        # Endpoint: POST {domain_url}/oauth2/v1/token
        # Grant type: urn:ietf:params:oauth:grant-type:jwt-bearer

        TOKEN_URL="${OCI_DOMAIN_URL}/oauth2/v1/token"

        # Create Basic Auth header
        BASIC_AUTH=$(printf '%s:%s' "$OCI_CLIENT_ID" "$OCI_CLIENT_SECRET" | base64 -w0)

        # Exchange token using JWT Bearer grant
        RESPONSE=$(curl -s -X POST "$TOKEN_URL" \
          -H "Authorization: Basic ${BASIC_AUTH}" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer" \
          -d "assertion=${GITHUB_OIDC_TOKEN}" \
          -d "scope=urn:opc:idm:__myscopes__" 2>&1 || echo "")

        # Debug: show response structure (without sensitive data)
        echo "Response status: $(echo "$RESPONSE" | jq -r '.error // "ok"' 2>/dev/null || echo "parse_error")"

        ACCESS_TOKEN=$(echo "$RESPONSE" | jq -r '.access_token // ""' 2>/dev/null || echo "")
        ERROR=$(echo "$RESPONSE" | jq -r '.error // ""' 2>/dev/null || echo "")
        ERROR_DESC=$(echo "$RESPONSE" | jq -r '.error_description // ""' 2>/dev/null || echo "")

        if [[ -n "$ACCESS_TOKEN" && "$ACCESS_TOKEN" != "null" && "$ACCESS_TOKEN" != "" ]]; then
          echo "✓ Successfully obtained OCI Access Token via OIDC"
          echo "auth_method=oidc" >> "$GITHUB_OUTPUT"

          # Store access token (multiline safe)
          output_multiline "session_token" "$ACCESS_TOKEN"

          # For OIDC, we don't need the API key but keep it for compatibility
          output_multiline "session_key" "$OCI_API_KEY_CONTENT"
        else
          echo "::warning::OIDC token exchange failed"
          if [[ -n "$ERROR" ]]; then
            echo "::warning::Error: $ERROR - $ERROR_DESC"
          fi
          echo "::warning::Falling back to API key authentication"
          echo "auth_method=api_key" >> "$GITHUB_OUTPUT"
          echo "session_token=" >> "$GITHUB_OUTPUT"
          output_multiline "session_key" "$OCI_API_KEY_CONTENT"
        fi
