# External Secret for Nextcloud - from Doppler service-nextcloud
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-secrets
  namespace: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-service-nextcloud
  target:
    name: nextcloud-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        NEXTCLOUD_ADMIN_USER: "{{ .NEXTCLOUD_ADMIN_USER }}"
        NEXTCLOUD_ADMIN_PASSWORD: "{{ .NEXTCLOUD_ADMIN_PASSWORD }}"
        POSTGRES_PASSWORD: "{{ .NEXTCLOUD_POSTGRES_PASSWORD }}"
        OBJECTSTORE_S3_KEY: "{{ .OBJECTSTORE_S3_KEY }}"
        OBJECTSTORE_S3_SECRET: "{{ .OBJECTSTORE_S3_SECRET }}"
  data:
    - secretKey: NEXTCLOUD_ADMIN_USER
      remoteRef:
        key: NEXTCLOUD_ADMIN_USER
    - secretKey: NEXTCLOUD_ADMIN_PASSWORD
      remoteRef:
        key: NEXTCLOUD_ADMIN_PASSWORD
    - secretKey: NEXTCLOUD_POSTGRES_PASSWORD
      remoteRef:
        key: NEXTCLOUD_POSTGRES_PASSWORD
    - secretKey: OBJECTSTORE_S3_KEY
      remoteRef:
        key: OBJECTSTORE_S3_KEY
    - secretKey: OBJECTSTORE_S3_SECRET
      remoteRef:
        key: OBJECTSTORE_S3_SECRET
