import pytest
from shared.utils.schemas import StorageConfig, StorageAccess, StorageTier
from shared.apps.common.storage_provisioner import (
    StorageProvisionerFactory,
    DefaultProvisioner,
    HetznerSMBProvisioner,
)


class MockProvider:
    pass


class MockResource:
    pass


def test_default_provisioner_access_modes():
    # Test ReadWriteOnce
    storage_private = StorageConfig(
        name="data",
        tier=StorageTier.PERSISTENT,
        access=StorageAccess.PRIVATE,
        size="1Gi",
    )
    provisioner = StorageProvisionerFactory.get_provisioner(storage_private)
    assert isinstance(provisioner, DefaultProvisioner)
    assert provisioner._get_access_modes(storage_private) == ["ReadWriteOnce"]

    # Test ReadWriteMany (Shared)
    storage_shared = StorageConfig(
        name="data_shared",
        tier=StorageTier.PERSISTENT,
        access=StorageAccess.SHARED,
        size="1Gi",
    )
    assert provisioner._get_access_modes(storage_shared) == ["ReadWriteMany"]


def test_hetzner_provisioner_creation():
    storage_hetzner = StorageConfig(
        name="data",
        tier=StorageTier.EXTERNAL,
        access=StorageAccess.SHARED,
        storage_class="hetzner-smb",
        size="1Ti",
    )
    provisioner = StorageProvisionerFactory.get_provisioner(storage_hetzner)
    assert isinstance(provisioner, HetznerSMBProvisioner)
    assert provisioner._get_access_modes(storage_hetzner) == ["ReadWriteMany"]


def test_hetzner_private_smb_access_modes():
    storage_hetzner_private = StorageConfig(
        name="data",
        tier=StorageTier.EXTERNAL,
        access=StorageAccess.PRIVATE_SMB,
        storage_class="hetzner-smb",
        size="1Ti",
    )
    provisioner = StorageProvisionerFactory.get_provisioner(storage_hetzner_private)
    assert isinstance(provisioner, HetznerSMBProvisioner)
    assert provisioner._get_access_modes(storage_hetzner_private) == ["ReadWriteMany"]


def test_pvc_naming_consistency():
    """
    Test that PVC names generated by StorageProvisioner match what's expected in apps.yaml.

    This prevents Helm adoption failures where:
    - Pulumi creates PVC with name: {app}-{storage}
    - Helm chart expects a different name via volumeClaimName/existingClaim

    The test validates that the PVC naming pattern is consistent.
    Only checks persistence keys that MATCH the storage name (case-insensitive).
    """
    from shared.apps.loader import AppLoader

    loader = AppLoader()
    apps = loader.load()

    errors = []

    for app in apps:
        if not app.helm or not app.storage:
            continue

        helm_values = app.helm.values or {}
        persistence = helm_values.get("persistence", {})

        # Build a map of storage name -> expected PVC name
        storage_pvc_map = {s.name: f"{app.name}-{s.name}" for s in app.storage}

        # Check each persistence key
        for pvc_key, val in persistence.items():
            if not isinstance(val, dict):
                continue

            # Find matching storage (key should match storage name exactly or be a clear variant)
            matching_storage = None
            # Sort by length descending to prefer longer matches
            sorted_storages = sorted(
                storage_pvc_map.items(), key=lambda x: len(x[0]), reverse=True
            )

            for storage_name, expected_pvc in sorted_storages:
                # Exact match (case insensitive) - highest priority
                if storage_name.lower() == pvc_key.lower():
                    matching_storage = storage_name
                    break
                # Or if the pvc_key contains the storage name (e.g., "homarrDatabase" contains "database")
                if pvc_key.lower() in storage_name.lower():
                    matching_storage = storage_name
                    break

            if not matching_storage:
                # No matching storage - this persistence key is for something else
                continue

            expected_pvc_name = storage_pvc_map[matching_storage]

            # Check volumeClaimName (homarr v2 style)
            if "volumeClaimName" in val:
                actual_name = val["volumeClaimName"]
                if actual_name != expected_pvc_name:
                    errors.append(
                        f"App '{app.name}': volumeClaimName '{actual_name}' "
                        f"doesn't match expected '{expected_pvc_name}' "
                        f"(storage: {matching_storage}, key: {pvc_key})"
                    )

            # Check existingClaim (app-template style)
            if "existingClaim" in val:
                actual_name = val["existingClaim"]
                if actual_name != expected_pvc_name:
                    errors.append(
                        f"App '{app.name}': existingClaim '{actual_name}' "
                        f"doesn't match expected '{expected_pvc_name}' "
                        f"(storage: {matching_storage}, key: {pvc_key})"
                    )

    if errors:
        pytest.fail(
            "PVC naming inconsistencies detected:\n"
            + "\n".join(f"  - {e}" for e in errors)
        )


def test_pvc_helm_annotations():
    """
    Test that PVCs created by provisioner include Helm annotations.

    This ensures Helm can adopt PVCs created by Pulumi without:
    'invalid ownership metadata; key app.kubernetes.io/managed-by must equal Helm'
    """
    from pathlib import Path

    # Read the storage_provisioner.py to verify it adds Helm annotations
    provisioner_path = (
        Path(__file__).parent.parent.parent
        / "shared"
        / "apps"
        / "common"
        / "storage_provisioner.py"
    )
    content = provisioner_path.read_text()

    # Verify Helm annotations are added
    assert "meta.helm.sh/release-name" in content, (
        "StorageProvisioner must add 'meta.helm.sh/release-name' annotation"
    )
    assert "meta.helm.sh/release-namespace" in content, (
        "StorageProvisioner must add 'meta.helm.sh/release-namespace' annotation"
    )
