---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-agent
  namespace: o11y
data:
  agent.yaml: |
    metrics:
      configs:
        - name: integrations
          remote_write:
            - url: ${GRAFANA_CLOUD_METRICS_URL}
              basic_auth:
                username: ${GRAFANA_CLOUD_USERNAME}
                password: ${GRAFANA_CLOUD_API_KEY}
          scrape_configs:
            # Kubernetes API Server
            - job_name: kubernetes-apiservers
              kubernetes_sd_configs:
                - role: endpoints
              scheme: https
              tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecure_skip_verify: false
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              relabel_configs:
                - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
                  action: keep
                  regex: default;kubernetes;https

            # Kubernetes Nodes
            - job_name: kubernetes-nodes
              kubernetes_sd_configs:
                - role: node
              scheme: https
              tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecure_skip_verify: false
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              relabel_configs:
                - action: labelmap
                  regex: __meta_kubernetes_node_label_(.+)

            # Kubernetes Pods
            - job_name: kubernetes-pods
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                  action: keep
                  regex: true
                - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
                  action: replace
                  target_label: __metrics_path__
                  regex: (.+)
                - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
                  action: replace
                  regex: ([^:]+)(?::\d+)?;(\d+)
                  replacement: $1:$2
                  target_label: __address__
                - action: labelmap
                  regex: __meta_kubernetes_pod_label_(.+)
                - source_labels: [__meta_kubernetes_namespace]
                  action: replace
                  target_label: kubernetes_namespace
                - source_labels: [__meta_kubernetes_pod_name]
                  action: replace
                  target_label: kubernetes_pod_name

            # Kubernetes Resources
            - job_name: kubernetes-resources
              kubernetes_sd_configs:
                - role: resources
              scrape_interval: 60s
              relabel_configs:
                - action: keep
                  regex: true
                  source_labels: [__meta_kubernetes_managed_by]

            # node-exporter
            - job_name: node-exporter
              kubernetes_sd_configs:
                - role: pod
                  namespaces:
                    names:
                      - o11y
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_container_name]
                  action: keep
                  regex: node-exporter

            # kubelet
            - job_name: kubelet
              kubernetes_sd_configs:
                - role: node
              scheme: https
              tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecure_skip_verify: false
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              metrics_path: /metrics

            # cadvisor
            - job_name: cadvisor
              kubernetes_sd_configs:
                - role: node
              scheme: https
              tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecure_skip_verify: false
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              metrics_path: /metrics/cadvisor

    logs:
      configs:
        - name: kubernetes
          positions:
            filename: /tmp/positions.yaml
          scrape_configs:
            - job_name: kubernetes-pods
              kubernetes_sd_configs:
                - role: pod
              pipeline_stages:
                - docker: {}
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_name]
                  action: replace
                  target_label: pod
                - source_labels: [__meta_kubernetes_namespace]
                  action: replace
                  target_label: namespace
          clients:
            - url: http://loki.o11y.svc.cluster.local:3100/loki/api/v1/push
              # basic_auth:
              #   username: ${LOKI_USERNAME}
              #   password: ${LOKI_API_KEY}

    integrations:
      node_exporter:
        enabled: true
        extra_args:
          - --collector.disable-defaults
          - --collector.cpu
          - --collector.meminfo
          - --collector.disk
          - --collector.filesystem
          - --collector.loadavg
          - --collector.netdev
          - --collector.stat
          - --collector.time
          - --collector.uname
