---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-cloud-credentials
  namespace: o11y
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: SecretStore
  target:
    name: grafana-cloud-credentials
    creationPolicy: Owner
  data:
    - secretKey: GRAFANA_CLOUD_METRICS_URL
      remoteRef:
        key: GRAFANA_CLOUD_METRICS_URL
    - secretKey: GRAFANA_CLOUD_USERNAME
      remoteRef:
        key: GRAFANA_CLOUD_USERNAME
    - secretKey: GRAFANA_CLOUD_API_KEY
      remoteRef:
        key: GRAFANA_CLOUD_API_KEY
    - secretKey: GRAFANA_CLOUD_LOGS_URL
      remoteRef:
        key: GRAFANA_CLOUD_LOGS_URL
    - secretKey: LOKI_USERNAME
      remoteRef:
        key: LOKI_USERNAME
    - secretKey: LOKI_API_KEY
      remoteRef:
        key: LOKI_API_KEY
