# LiteLLM credentials (API keys for Synthetic, OpenAI, etc.)
# See: https://registry.terraform.io/providers/ncecere/litellm/latest/docs/resources/credential

# =============================================================================
# OpenClaw — dedicated API key for LiteLLM proxy
# =============================================================================
# OpenClaw uses this key to call the LiteLLM proxy. Key is generated by LiteLLM
# if openclaw_litellm_key is empty; otherwise the provided value is used.
# After apply: set this key in OpenClaw config (e.g. LITELLM_API_KEY or env).
# =============================================================================
resource "litellm_key" "openclaw" {
  key_alias = "openclaw"
  key       = var.openclaw_litellm_key != "" ? var.openclaw_litellm_key : null
}

output "openclaw_litellm_key" {
  description = "LiteLLM API key for OpenClaw. Set in OpenClaw config (e.g. LITELLM_API_KEY)."
  value       = litellm_key.openclaw.key
  sensitive   = true
}
