variable "litellm_url" {
  type        = string
  description = "LiteLLM proxy base URL (e.g. https://llm.smadja.dev or http://litellm:4000 when running from same network)"
  default     = ""
}

variable "litellm_master_key" {
  type        = string
  sensitive   = true
  description = "LiteLLM master key for admin API. Prefer env LITELLM_MASTER_KEY; never commit."
  default     = ""
}

# Optional: pre-generated key for OpenClaw. If empty, a key is generated by LiteLLM and output.
variable "openclaw_litellm_key" {
  type        = string
  sensitive   = true
  description = "Optional API key for OpenClaw to call LiteLLM. If empty, Terraform creates a key via LiteLLM API and outputs it."
  default     = ""
}
