apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-secrets
  namespace: o11y
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: grafana-secrets
    creationPolicy: Owner
  data:
    - secretKey: GRAFANA_ADMIN_USER
      remoteRef:
        key: GRAFANA_ADMIN_USER
    - secretKey: GRAFANA_ADMIN_PASSWORD
      remoteRef:
        key: GRAFANA_ADMIN_PASSWORD
