# Authentik - Production overlay
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra

resources:
  - ../../base

patches:
  - target:
      kind: HelmRelease
    patch: |
      - op: replace
        path: /spec/values/ingress/hosts
        value:
          - auth.smadja.dev
      - op: replace
        path: /spec/values/ingress/tls/0/hosts
        value:
          - auth.smadja.dev
