apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
  namespace: network
spec:
  endpoints:
  - dnsName: ingress-ext.smadja.dev
    recordType: CNAME
    targets:
    - d4176ff3-bcaf-4d59-97ae-6c144d6399b7.cfargotunnel.com
  - dnsName: pangolin.smadja.dev
    recordType: CNAME
    targets:
    - d4176ff3-bcaf-4d59-97ae-6c144d6399b7.cfargotunnel.com
