---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-secret
  namespace: network
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: external-dns-secret
    template:
      engineVersion: v2
      data:
        api-token: "{{ .CLOUDFLARE_API_TOKEN }}"
  data:
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: cloudflare
        property: CLOUDFLARE_API_TOKEN
