"""
Dynamic secrets verification tests.
"""
import subprocess
import json
import pytest

@pytest.fixture(scope="session")
def check_doppler_store(k8s_available):
    if not k8s_available:
        pytest.skip("Kubernetes cluster not available")

    # Check ClusterSecretStore
    res = subprocess.run(["kubectl", "get", "clustersecretstore", "doppler", "-o", "json"],
                         capture_output=True, text=True)
    if res.returncode != 0:
        pytest.skip("Doppler ClusterSecretStore not found")

    store = json.loads(res.stdout)
    conditions = store.get("status", {}).get("conditions", [])
    ready = next((c for c in conditions if c.get("type") == "Ready" and c.get("status") == "True"), None)
    if not ready:
        pytest.fail("Doppler ClusterSecretStore is not Ready")

def test_external_secrets_created(test_case, check_doppler_store):
    """Verify that ExternalSecret resources are created for each secret in apps.yaml."""
    if not test_case.secrets:
        pytest.skip(f"No secrets defined for {test_case.name}")

    for secret in test_case.secrets:
        res = subprocess.run(
            ["kubectl", "get", "externalsecret", secret.name, "-n", test_case.namespace, "-o", "json"],
            capture_output=True, text=True
        )
        assert res.returncode == 0, f"ExternalSecret {secret.name} not found in {test_case.namespace}"

        # Check status
        data = json.loads(res.stdout)
        conditions = data.get("status", {}).get("conditions", [])
        secret_synced = next((c for c in conditions if c.get("type") == "SecretSynced" and c.get("status") == "True"), None)
        # We don't fail here if not synced, just report it - networking might be transient
        if not secret_synced:
            print(f"Warning: ExternalSecret {secret.name} is not yet synced in {test_case.namespace}")

def test_kubernetes_secrets_exist(test_case, check_doppler_store):
    """Verify that the actual K8s Secret resources generated by ExternalSecrets exist."""
    if not test_case.secrets:
        pytest.skip(f"No secrets defined for {test_case.name}")

    for secret in test_case.secrets:
        res = subprocess.run(
            ["kubectl", "get", "secret", secret.name, "-n", test_case.namespace],
            capture_output=True, text=True
        )
        # In a real run, this might be false if ExternalSecrets hasn't finished syncing
        # but for a CI/CD check after deployment, it should be true.
        assert res.returncode == 0, f"K8s Secret {secret.name} not found in {test_case.namespace}"
