apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: infra
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: authentik-values
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        values.yaml: |
          authentik:
            secret_key: "{{ .AUTHENTIK_SECRET_KEY }}"
          externalDatabase:
            host: "{{ .AUTHENTIK_POSTGRES_HOST }}"
            port: "{{ .AUTHENTIK_POSTGRES_PORT }}"
            database: "{{ .AUTHENTIK_POSTGRES_NAME }}"
            username: "{{ .AUTHENTIK_POSTGRES_USER }}"
            password: "{{ .AUTHENTIK_POSTGRES_PASSWORD }}"
            sslmode: require
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: AUTHENTIK_SECRET_KEY
    - secretKey: AUTHENTIK_POSTGRES_PASSWORD
      remoteRef:
        key: AUTHENTIK_POSTGRES_PASSWORD
    - secretKey: AUTHENTIK_POSTGRES_HOST
      remoteRef:
        key: AUTHENTIK_POSTGRES_HOST
    - secretKey: AUTHENTIK_POSTGRES_PORT
      remoteRef:
        key: AUTHENTIK_POSTGRES_PORT
    - secretKey: AUTHENTIK_POSTGRES_NAME
      remoteRef:
        key: AUTHENTIK_POSTGRES_NAME
    - secretKey: AUTHENTIK_POSTGRES_USER
      remoteRef:
        key: AUTHENTIK_POSTGRES_USER
