apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: infra
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: authentik-values
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"
        AUTHENTIK_POSTGRESQL__HOST: "{{ .AUTHENTIK_POSTGRES_HOST }}"
        AUTHENTIK_POSTGRESQL__PORT: "{{ .AUTHENTIK_POSTGRES_PORT }}"
        AUTHENTIK_POSTGRESQL__NAME: "{{ .AUTHENTIK_POSTGRES_NAME }}"
        AUTHENTIK_POSTGRESQL__USER: "{{ .AUTHENTIK_POSTGRES_USER }}"
        AUTHENTIK_POSTGRESQL__PASSWORD: "{{ .AUTHENTIK_POSTGRES_PASSWORD }}"
        AUTHENTIK_POSTGRESQL__CONN_MAX_AGE: "0"
        AUTHENTIK_POSTGRESQL__DISABLE_SERVER_SIDE_CURSORS: "true"
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: AUTHENTIK_SECRET_KEY
    - secretKey: AUTHENTIK_POSTGRES_PASSWORD
      remoteRef:
        key: AUTHENTIK_POSTGRES_PASSWORD
    - secretKey: AUTHENTIK_POSTGRES_HOST
      remoteRef:
        key: AUTHENTIK_POSTGRES_HOST
    - secretKey: AUTHENTIK_POSTGRES_PORT
      remoteRef:
        key: AUTHENTIK_POSTGRES_PORT
    - secretKey: AUTHENTIK_POSTGRES_NAME
      remoteRef:
        key: AUTHENTIK_POSTGRES_NAME
    - secretKey: AUTHENTIK_POSTGRES_USER
      remoteRef:
        key: AUTHENTIK_POSTGRES_USER
