apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: infra
spec:
  interval: 1h
  timeout: 10m
  releaseName: authentik
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  values:
    postgresql:
      enabled: false
    redis:
      enabled: true
    global:
      env:
        - name: AUTHENTIK_POSTGRESQL__HOST
          value: "134.122.58.11"
        - name: AUTHENTIK_POSTGRESQL__PORT
          value: "14351"
        - name: AUTHENTIK_POSTGRESQL__NAME
          value: "defaultdb"
        - name: AUTHENTIK_POSTGRESQL__USER
          value: "avnadmin"
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-values
              key: AUTHENTIK_POSTGRESQL__PASSWORD
        - name: AUTHENTIK_POSTGRESQL__SSLMODE
          value: "require"
        - name: AUTHENTIK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: authentik-values
              key: AUTHENTIK_SECRET_KEY
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    force: false
    remediation:
      retries: 3
      remediateLastFailure: true
  driftDetection:
    mode: enabled
