apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: infra
spec:
  interval: 1h
  releaseName: authentik
  chart:
    spec:
      chart: authentik
      version: "2024.10.3"
      sourceRef:
        kind: HelmRepository
        name: authentik
  values:
    authentik:
      secret_key: secret-key-placeholder
    postgresql:
      enabled: true
      auth:
        database: authentik
        username: authentik
    redis:
      enabled: true
    ingress:
      enabled: true
      className: traefik
      hosts:
        - auth.smadja.dev
      tls:
        - secretName: authentik-tls
          hosts:
            - auth.smadja.dev
