apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: infra
spec:
  interval: 1h
  timeout: 10m
  releaseName: authentik
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  values:
    postgresql:
      enabled: false
    redis:
      enabled: true
    global:
      env:
        - name: AUTHENTIK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: authentik-values
              key: AUTHENTIK_SECRET_KEY
        - name: AUTHENTIK_PGSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: authentik-external-db
              key: AUTHENTIK_POSTGRESQL__HOST
        - name: AUTHENTIK_PGSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: authentik-external-db
              key: AUTHENTIK_POSTGRESQL__PORT
        - name: AUTHENTIK_PGSQL_NAME
          valueFrom:
            configMapKeyRef:
              name: authentik-external-db
              key: AUTHENTIK_POSTGRESQL__NAME
        - name: AUTHENTIK_PGSQL_USER
          valueFrom:
            configMapKeyRef:
              name: authentik-external-db
              key: AUTHENTIK_POSTGRESQL__USER
        - name: AUTHENTIK_PGSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-values
              key: AUTHENTIK_POSTGRESQL__PASSWORD
    authentik:
      postgresql:
        host: env://AUTHENTIK_PGSQL_HOST
        port: env://AUTHENTIK_PGSQL_PORT
        name: env://AUTHENTIK_PGSQL_NAME
        user: env://AUTHENTIK_PGSQL_USER
        password: env://AUTHENTIK_PGSQL_PASSWORD
      secret_key: env://AUTHENTIK_SECRET_KEY
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    force: false
    remediation:
      retries: 3
      remediateLastFailure: true
  driftDetection:
    mode: enabled
