apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: infra
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`auth.smadja.dev`)
      kind: Rule
      services:
          port: 80
  tls:
    certResolver: cloudflare
    domains:
      - main: smadja.dev
        sans:
          - "*.smadja.dev"
