name: 'Setup Terraform'
description: 'Setup Terraform with specific version'
inputs:
  terraform-version:
    description: 'Terraform version'
    required: false
    default: '1.14.4'
runs:
  using: 'composite'
  steps:
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}
