# Composite action to authenticate with Authentik OAuth2 (client_credentials)
# Used by: Omni GitOps, Terraform Authentik, ArgoCD, and other CI/CD workflows
# Uses the generic "ci-automation" OAuth2 provider
#
# Prerequisites:
#   1. Create OAuth2 provider "ci-automation" in Authentik (via Terraform)
#   2. Enable "Client credentials" grant type in Authentik UI
#   3. Provide client_id and client_secret via inputs (from OCI Vault) or GitHub Secrets (fallback)
#
# Usage in workflow (with OCI Vault):
#   steps:
#     - uses: ./.github/actions/oci-vault-secrets
#       id: vault-secrets
#       with:
#         secrets: 'authentik_oauth2_client_id,authentik_oauth2_client_secret'
#         ...
#     - uses: ./.github/actions/authentik-oauth2-auth
#       id: authentik-auth
#       with:
#         client_id: ${{ steps.vault-secrets.outputs.authentik_oauth2_client_id }}
#         client_secret: ${{ steps.vault-secrets.outputs.authentik_oauth2_client_secret }}
#         scope: "goauthentik.io/api"  # Optional
#
# Usage in workflow (fallback to GitHub Secrets):
#   steps:
#     - uses: ./.github/actions/authentik-oauth2-auth
#       id: authentik-auth
#       with:
#         scope: "goauthentik.io/api"  # Optional, will use GitHub Secrets if client_id/secret not provided
#
# Outputs:
#   access_token: Authentik OAuth2 access token (for use as AUTHENTIK_TOKEN or OMNI_TOKEN, etc.)
#   token_source: "oauth2" if successful, "static" if fallback to AUTHENTIK_TOKEN

name: 'Authentik OAuth2 Authentication'
description: 'Obtains Authentik OAuth2 access token via client_credentials flow for CI/CD automation'

inputs:
  client_id:
    description: 'OAuth2 client_id (from OCI Vault or GitHub Secrets). If not provided, uses CI_AUTOMATION_AUTHENTIK_CLIENT_ID secret.'
    required: false
  client_secret:
    description: 'OAuth2 client_secret (from OCI Vault or GitHub Secrets). If not provided, uses CI_AUTOMATION_AUTHENTIK_CLIENT_SECRET secret.'
    required: false
  scope:
    description: 'OAuth2 scope to request (default: goauthentik.io/api)'
    required: false
    default: 'goauthentik.io/api'
  issuer_url:
    description: 'Authentik OAuth2 issuer URL (default: https://auth.smadja.dev/application/o/ci-automation/)'
    required: false
    default: 'https://auth.smadja.dev/application/o/ci-automation/'

outputs:
  access_token:
    description: 'Authentik OAuth2 access token'
    value: ${{ steps.oauth2.outputs.access_token }}
  token_source:
    description: 'Source of token: oauth2 or static'
    value: ${{ steps.oauth2.outputs.token_source }}

runs:
  using: 'composite'
  steps:
    - name: Authenticate with Authentik OAuth2
      id: oauth2
      shell: bash
      env:
        CLIENT_ID: ${{ inputs.client_id || secrets.CI_AUTOMATION_AUTHENTIK_CLIENT_ID }}
        CLIENT_SECRET: ${{ inputs.client_secret || secrets.CI_AUTOMATION_AUTHENTIK_CLIENT_SECRET }}
        ISSUER_URL: ${{ inputs.issuer_url }}
        SCOPE: ${{ inputs.scope }}
      run: |
        # Try to get OAuth2 token (if provider exists)
        if [ -z "$CLIENT_ID" ] || [ -z "$CLIENT_SECRET" ]; then
          echo "::notice::OAuth2 client_id/client_secret not provided (neither via inputs nor GitHub Secrets), falling back to AUTHENTIK_TOKEN"
          echo "token_source=static" >> $GITHUB_OUTPUT
          exit 0
        fi

        echo "Obtaining Authentik OAuth2 token via client_credentials flow..."
        TOKEN_RESPONSE=$(curl -s -X POST "${ISSUER_URL}token/" \
          -u "${CLIENT_ID}:${CLIENT_SECRET}" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "grant_type=client_credentials" \
          -d "scope=${SCOPE}")

        ACCESS_TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r '.access_token // empty' 2>/dev/null || echo "")

        if [ -n "$ACCESS_TOKEN" ] && [ "$ACCESS_TOKEN" != "null" ]; then
          echo "✓ Authentik OAuth2 token obtained"
          echo "access_token=$ACCESS_TOKEN" >> $GITHUB_OUTPUT
          echo "token_source=oauth2" >> $GITHUB_OUTPUT
        else
          ERROR=$(echo "$TOKEN_RESPONSE" | jq -r '.error // "unknown"' 2>/dev/null || echo "parse_error")
          ERROR_DESC=$(echo "$TOKEN_RESPONSE" | jq -r '.error_description // ""' 2>/dev/null || echo "")
          echo "::warning::Failed to obtain OAuth2 token: $ERROR - $ERROR_DESC"
          echo "::warning::Falling back to static AUTHENTIK_TOKEN (if available)"
          echo "token_source=static" >> $GITHUB_OUTPUT
        fi
