#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# act-run.sh — Run GitHub Actions locally with OCI Vault secrets
#
# This script fetches secrets from OCI Vault and passes them to `act` for
# local testing of GitHub Actions workflows.
#
# Usage:
#   ./scripts/act-run.sh                           # List available workflows
#   ./scripts/act-run.sh -W .github/workflows/terraform-cloudflare.yml
#   ./scripts/act-run.sh -j validate               # Run specific job
#   ./scripts/act-run.sh -l                        # List jobs in workflow
#   ./scripts/act-run.sh --help                    # Show act help
#
# Prerequisites:
#   - act installed (brew install act)
#   - OCI CLI configured (~/.oci/config)
#   - Docker running
#
# The script:
#   1. Fetches secrets from OCI Vault
#   2. Creates temporary .secrets.act file
#   3. Runs act with the secrets
#   4. Cleans up the secrets file
# -----------------------------------------------------------------------------
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
SECRETS_FILE="$PROJECT_ROOT/.secrets.act"
ENV_FILE="$PROJECT_ROOT/.env.act"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Cleanup on exit
cleanup() {
  if [[ -f "$SECRETS_FILE" ]]; then
    rm -f "$SECRETS_FILE"
    echo -e "${GREEN}✓ Cleaned up secrets file${NC}"
  fi
}
trap cleanup EXIT

# Check dependencies
check_dependencies() {
  if ! command -v act &>/dev/null; then
    echo -e "${RED}Error: act is not installed${NC}"
    echo "Install with: brew install act"
    exit 1
  fi

  if ! command -v oci &>/dev/null; then
    echo -e "${RED}Error: OCI CLI is not installed${NC}"
    exit 1
  fi

  if ! docker info &>/dev/null; then
    echo -e "${RED}Error: Docker is not running${NC}"
    exit 1
  fi
}

# Fetch a secret from OCI Vault
fetch_secret() {
  local secret_name="$1"
  local compartment_id
  compartment_id=$(oci iam compartment list --query 'data[0].id' --raw-output 2>/dev/null || echo "")

  if [[ -z "$compartment_id" ]]; then
    # Use tenancy as compartment
    compartment_id=$(grep -E '^tenancy=' ~/.oci/config | head -1 | cut -d'=' -f2)
  fi

  local secret_ocid
  secret_ocid=$(oci vault secret list \
    --compartment-id "$compartment_id" \
    --name "$secret_name" \
    --lifecycle-state ACTIVE \
    --query 'data[0].id' \
    --raw-output 2>/dev/null || echo "")

  if [[ -z "$secret_ocid" || "$secret_ocid" == "null" ]]; then
    echo ""
    return
  fi

  local secret_content
  secret_content=$(oci secrets secret-bundle get \
    --secret-id "$secret_ocid" \
    --stage CURRENT \
    --query 'data."secret-bundle-content".content' \
    --raw-output 2>/dev/null || echo "")

  if [[ -n "$secret_content" && "$secret_content" != "null" ]]; then
    echo "$secret_content" | base64 -d
  fi
}

# Generate secrets file from OCI Vault
generate_secrets_file() {
  echo -e "${YELLOW}Fetching secrets from OCI Vault...${NC}"

  # OCI auth secrets (from local config)
  local oci_config="$HOME/.oci/config"
  local oci_user oci_tenancy oci_fingerprint oci_region

  if [[ -f "$oci_config" ]]; then
    oci_user=$(grep -E '^user=' "$oci_config" | head -1 | cut -d'=' -f2)
    oci_tenancy=$(grep -E '^tenancy=' "$oci_config" | head -1 | cut -d'=' -f2)
    oci_fingerprint=$(grep -E '^fingerprint=' "$oci_config" | head -1 | cut -d'=' -f2)
    oci_region=$(grep -E '^region=' "$oci_config" | head -1 | cut -d'=' -f2)
  fi

  # Start secrets file
  cat > "$SECRETS_FILE" << EOF
# Generated by scripts/act-run.sh - DO NOT COMMIT
# OCI Auth (from ~/.oci/config)
OCI_CLI_USER=$oci_user
OCI_CLI_TENANCY=$oci_tenancy
OCI_CLI_FINGERPRINT=$oci_fingerprint
OCI_CLI_REGION=${oci_region:-eu-paris-1}
OCI_COMPARTMENT_ID=$oci_tenancy
EOF

  # OCI Object Storage namespace
  local namespace
  namespace=$(oci os ns get --query 'data' --raw-output 2>/dev/null || echo "")
  echo "OCI_OBJECT_STORAGE_NAMESPACE=$namespace" >> "$SECRETS_FILE"

  # Session token (if using session auth)
  local session_token_file="$HOME/.oci/session_token"
  local session_key_file="$HOME/.oci/session_key.pem"

  if [[ -f "$session_token_file" ]]; then
    echo "OCI_SESSION_TOKEN=$(cat "$session_token_file")" >> "$SECRETS_FILE"
  fi

  if [[ -f "$session_key_file" ]]; then
    # Encode multiline secret as single line (escaped newlines)
    local key_content
    key_content=$(awk '{printf "%s\\n", $0}' "$session_key_file")
    echo "OCI_SESSION_PRIVATE_KEY=$key_content" >> "$SECRETS_FILE"
  fi

  # SSH public key (from typical location)
  local ssh_pub_key="$HOME/.ssh/oci-homelab.pub"
  if [[ -f "$ssh_pub_key" ]]; then
    echo "SSH_PUBLIC_KEY=$(cat "$ssh_pub_key")" >> "$SECRETS_FILE"
  fi

  # Fetch secrets from OCI Vault
  echo -n "  cloudflare_api_token... "
  local cf_token
  cf_token=$(fetch_secret "homelab-cloudflare-api-token")
  if [[ -n "$cf_token" ]]; then
    echo "CLOUDFLARE_API_TOKEN=$cf_token" >> "$SECRETS_FILE"
    echo -e "${GREEN}✓${NC}"
  else
    echo -e "${YELLOW}skipped${NC}"
  fi

  echo -n "  omni_db_user... "
  local omni_user
  omni_user=$(fetch_secret "homelab-omni-db-user")
  if [[ -n "$omni_user" ]]; then
    echo "OMNI_DB_USER=$omni_user" >> "$SECRETS_FILE"
    echo -e "${GREEN}✓${NC}"
  else
    echo -e "${YELLOW}skipped${NC}"
  fi

  echo -n "  omni_db_password... "
  local omni_pass
  omni_pass=$(fetch_secret "homelab-omni-db-password")
  if [[ -n "$omni_pass" ]]; then
    echo "OMNI_DB_PASSWORD=$omni_pass" >> "$SECRETS_FILE"
    echo -e "${GREEN}✓${NC}"
  else
    echo -e "${YELLOW}skipped${NC}"
  fi

  echo -n "  omni_db_name... "
  local omni_name
  omni_name=$(fetch_secret "homelab-omni-db-name")
  if [[ -n "$omni_name" ]]; then
    echo "OMNI_DB_NAME=$omni_name" >> "$SECRETS_FILE"
    echo -e "${GREEN}✓${NC}"
  else
    echo -e "${YELLOW}skipped${NC}"
  fi

  echo -n "  oci_mgmt_ssh_private_key... "
  local ssh_key
  ssh_key=$(fetch_secret "homelab-oci-mgmt-ssh-private-key")
  if [[ -n "$ssh_key" ]]; then
    # Encode multiline secret as single line (escaped newlines)
    local escaped_key
    escaped_key=$(echo "$ssh_key" | awk '{printf "%s\\n", $0}')
    echo "OCI_MGMT_SSH_PRIVATE_KEY=$escaped_key" >> "$SECRETS_FILE"
    echo -e "${GREEN}✓${NC}"
  else
    echo -e "${YELLOW}skipped${NC}"
  fi

  chmod 600 "$SECRETS_FILE"
  echo -e "${GREEN}✓ Secrets file generated${NC}"
}

# Create env file if not exists
create_env_file() {
  if [[ ! -f "$ENV_FILE" ]]; then
    cat > "$ENV_FILE" << EOF
# Environment variables for act
# This file is loaded by act for non-secret environment variables
GITHUB_REPOSITORY=SmadjaPaul/homelab
GITHUB_REPOSITORY_OWNER=SmadjaPaul
EOF
    echo -e "${GREEN}✓ Created .env.act${NC}"
  fi
}

# Main
main() {
  cd "$PROJECT_ROOT"

  check_dependencies
  create_env_file
  generate_secrets_file

  echo ""
  echo -e "${GREEN}Running act...${NC}"
  echo "----------------------------------------"

  # Run act with all arguments passed through
  act "$@"
}

main "$@"
