apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-creds
  namespace: cloudflared
type: Opaque
stringData:
  tunnel-token: eyJhIjoiYTk4ZWZiMTA2NWFkM2FlNmI3MjU5ZGNlNzVmMmE5ODAiLCJ0IjoiNjRlMGI4NjItMzVmMy00NWU4LWFiN2MtZjFlZWU2NjA5ZWFiIiwicyI6IldVbWVFcDRzWUdmS0RGSTZWdHd3aXY5WXM5MUdKNFRhYURHcFVVUHVJZEw1Z2lOSkNBMDV3WTRRTitqQThjbGUvWTdtcG9uYlhlbEFEK1hhcW9kaHJ3PT0ifQ==
  credentials.json: |
    {
      "AccountTag": "a98efb1065ad3ae6b7259dce75f2a980",
      "TunnelID": "64e0b862-35f3-45e8-ab7c-f1eee6609eab",
      "TunnelSecret": "WUmeEp4sYGfKDFI6Vtwwiv9Ys91GJ4TaaDGpUUPuIdL5giNJCA05wY4QN+jA8cle/Y7mponbXelAD+Xaqodhrw=="
    }
