apiVersion: v1
kind: Namespace
metadata:
  name: cloudflared
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-creds
  namespace: cloudflared
type: Opaque
stringData:
  credentials.json: |
    {
      "AccountTag": "a98efb1065ad3ae6b7259dce75f2a980",
      "TunnelID": "64e0b862-35f3-45e8-ab7c-f1eee6609eab",
      "TunnelSecret": "WUmeEp4sYGfKDFI6Vtwwiv9Ys91GJ4TaaDGpUUPuIdL5giNJCA05wY4QN+jA8cle/Y7mponbXelAD+Xaqodhrw=="
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: 64e0b862-35f3-45e8-ab7c-f1eee6609eab
    credentials-file: /etc/cloudflared/credentials/credentials.json
    ingress:
      - hostname: auth.smadja.dev
        service: http://authentik-server.infra.svc.cluster.local:80
      - hostname: home.smadja.dev
        service: http://homepage.public.svc.cluster.local:80
      - service: http_status:404
